### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bjartwolf** [NathanielWroblewski/outrun#1]
Hi, hi wanted to tinker around with this as a basis for a small car game that I wanted to create to go along with https://www.youtube.com/watch?v=e0Rz5kihi8c 

Since the project does not have a license, I was wondering if it would be possible to license it as MIT or similar? 
I realize the assets such as music and cars, would not be covered, of course, those I would replace anyway, but the source looked like a nice place to start for a outrun-style clone....

**Comment by NathanielWroblewski** [comment]
Added in ad448ba4dfbd4d8e0d37e73dfa93a4a77445871b

**Comment by bjartwolf** [comment]
Thank you! I will send you the links if we make something cool with it and make sure to mention you in the title screen :)
